### ISSUE TITLE
More documentation please

### ISSUE THREAD

**Issue by nataliedawson** [CATH-summer-2017/django_CATH#4]
Please could you provide some more documentation for the following step:

> Configure your database connection (MySQL) in init/django_settings.py Update the config for rootsite by appending with those in init/.

For example, which lines do I need to edit in `tst/init/django_settings.py` and where do I get the django database connection information from.

Please could you clarify what is meant by 'appending with those in init/'.

**Comment by shouldsee** [comment]
Hi @nataliedawson : 
I've updated the [README](https://github.com/CATH-summer-2017/django_CATH) to include a detailed explanation on the dependency on MySQL in more detail and rephrase the "appending" process (which is really concatenation a file to the end of another). Please also check ["init/django_settings.py"](https://github.com/CATH-summer-2017/django_CATH/blob/master/init/django_settings.py) for recent added comments.
